name: pr-tests
on: [push]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
